### ISSUE TITLE
script fetches mp3 for sampling from the wrong folder

### ISSUE THREAD

**Issue by tolotos68** [seanap/Auto-M4B-Tool#11]
Hi, the conversion works fine, but the script doesn't always fetch the mp3-sample from the right folder (i.e. from a different audiobook) - this could possibly lead to a wrong bitrate... 

Any ideas?

Fresh Ubuntu 20.04 LTS in a QNAP Virtualization Station VM

[auto-m4b-tool.txt](https://github.com/seanap/Auto-M4B-Tool/files/8366385/auto-m4b-tool.txt)

**Comment by seanap** [comment]
I noticed something was up with this but haven't found a solution.  Are you aware of any more elegant solutions than using ffmpg to sample the bitrate and pass that back into m4b-tool? Some people say that this is not the best way to do this but I don't fully understand why https://stackoverflow.com/questions/11196474/ffmpeg-conversion-keep-audio-bitrate

**Comment by tolotos68** [comment]
**The solution for the wrong folder was quite simple:** 
Just look in the specific subfolder $file: `mpthree=$(find "$file" -maxdepth 2 -type f -name "*.mp3" | head -n 1)` 
instead of looking into a random one with -maxdepth 2: `mpthree=$(find . -maxdepth 2 -type f -name "*.mp3" | head -n 1)`

since we don't have nested folders for our mp3s, we can simplify even more and omit -maxdepth 2:
`mpthree=$(find "$file" -type f -name "*.mp3" | head -n 1)`

**Comment by seanap** [comment]
Awesome! I'll push the changes through now.

Also, I'm working on integrating all this into a simple docker here, https://github.com/seanap/docker-m4b-tool still have some kinks to work out but the docker should make install so much easier.

**Comment by tolotos68** [comment]
> https://stackoverflow.com/questions/11196474/ffmpeg-conversion-keep-audio-bitrate

I made a little research - ffprobe should be OK, since it calculates the average bitrate which is important for VBR. Had a try with ffmpeg -I which unsurprisingly led to the same results.

**Comment by tolotos68** [comment]
> Awesome! I'll push the changes through now.
> 
> Also, I'm working on integrating all this into a simple docker here, https://github.com/seanap/docker-m4b-tool still have some kinks to work out but the docker should make install so much easier.

Cool - this would be really great!!!
