### ISSUE TITLE
Errors with the conversion

### ISSUE THREAD

**Issue by diablc** [seanap/Auto-M4B-Tool#2]
Terry Hayes/
Folder Detected
Sampling ./Terry Hayes/Terry Hayes - I Am Pilgrim - 01 - I Am Pilgrim A Thriller.mp3
/tmp/user.scripts/tmpScripts/Mp3merge/script: line 20: ffprobe: command not found
Bitrate =
The folder Terry Hayes will be merged to /untagged/Terry Hayes.m4b
Starting Conversion
the input device is not a TTY
mv: cannot stat '/mnt/user/Downloads/untagged/Terry Hayes.chapters.txt': No such file or directory
Finished Converting
Deleting duplicate mp3 audiobook folder

here is the log that I get.  I get a input device is not a TTY and ffprobe: command not found.  I have created a docker in Unraid.

**Comment by seanap** [comment]
Ah, yeah. You need to install ffmpeg.
```
# Install FFMPEG
sudo apt install ffmpeg -y
```
Without ffmpeg (to use ffprobe) you would just have to force a specific bit rate to apply to all books that come through.  So instead I use ffprobe to look at the mp3 file and get the bitrate, then I can apply that bitrate to the m4b settings.
