### ISSUE TITLE
Full list of Dropit rules?

### ISSUE THREAD

**Issue by tehniemer** [seanap/Auto-M4B-Tool#7]
Thanks for putting this guide together. I'm going through it and it seems that there are more than two rules for each of the Dropit associations, but I'm not finding the full list anywhere. 

![image](https://user-images.githubusercontent.com/11021632/133777821-b21a7bc7-1c56-4dbc-af0e-f5591e44cb9f.png)

**Comment by seanap** [comment]
The AudiobookCopy would be any extensions that you want to keep and do not need to do any conversions:
- *.m4b

The MP3Merge would be any extensions that you want to run through m4b-tool to convert to m4b:
- *.mp3;*.m4a;*.ogg;*.wav

I used Search Everything to sort my /original folder by filetype to see all the extensions I had. The above list should cover the majority of your needs but there are a ton of audio extensions out there, feel free to add what you need.

I did go back through and remove any video formats, as I do not want to convert them  and there isn't a folder created yet to put them in /Audiobooks until after we tag the audiofiles.  So any video or other (pdf, jpg, doc, etc) helper files are not handled by this automation.
